package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jedisct1/go-minisign"
)

const testPass = "correct-horse-battery"

// writeFile is a small helper for test fixtures.
func writeFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestKeygenSignVerifyRoundtrip(t *testing.T) {
	dir := t.TempDir()
	skFile := writeFile(t, dir, "minisign.key", "")
	pkFile := writeFile(t, dir, "minisign.pub", "")

	seckey, pubkey, err := generateKeyPair(testPass)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(skFile, seckey, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(pkFile, pubkey, 0o644); err != nil {
		t.Fatal(err)
	}

	// The generated secret key must decrypt with the passphrase and derive
	// the exact public key we wrote (C-reference layout, library decoder).
	sk, err := minisign.NewPrivateKeyFromFile(skFile)
	if err != nil {
		t.Fatalf("library cannot parse our key file: %v", err)
	}
	if !sk.IsEncrypted() {
		t.Fatal("expected encrypted key")
	}
	if err := sk.Decrypt(testPass); err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	pk, err := minisign.NewPublicKeyFromFile(pkFile)
	if err != nil {
		t.Fatal(err)
	}
	if sk.PublicKey() != pk {
		t.Fatal("derived public key does not match the encoded public key")
	}
	sk.Wipe()

	// Wrong passphrase must fail.
	sk2, _ := minisign.NewPrivateKeyFromFile(skFile)
	if err := sk2.Decrypt("wrong"); err == nil {
		t.Fatal("expected wrong-passphrase decrypt to fail")
	}

	// Sign a file, verify it, then verify that tampering breaks it.
	f := writeFile(t, dir, "artifact.bin", "rmmway-agent-linux-amd64\n")
	if err := signOne(skFile, testPass, f, "rmmway release test"); err != nil {
		t.Fatal(err)
	}
	comment, err := verifyOne(pkFile, f)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if !strings.Contains(comment, "rmmway release test") {
		t.Fatalf("untrusted comment missing release tag: %q", comment)
	}

	orig, err := os.ReadFile(f)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(f, append([]byte("tampered\n"), orig[7:]...), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := verifyOne(pkFile, f); err == nil {
		t.Fatal("expected tampered file to fail verification")
	}
}

// TestKeygenInteropWithCLIFixture signs a file with our tool and verifies
// it using ONLY the upstream library's decode/verify path (no code shared
// with the signer), the same way the reference minisign(1) CLI would.
func TestKeygenInteropWithCLIFixture(t *testing.T) {
	// Encrypted key pair generated by the real `minisign -G` (see the
	// upstream library's own fixtures).
	const cliSK = "untrusted comment: minisign encrypted secret key\nRWRTY0IyxYlIT2FS5i8PqThE9swBemvY94JDIMqo75UBK3XO/aUAAAACAAAAAAAAAEAAAAAAUhlw8nsT1tuVUekS6Je3iUwoWFdb1xiLonO35G66RiVvM/QgrBtnDa0Dhbt7H3oYMh4aFLiNxMs24gzXqHVsvRVthMeF08fN8r6siRdBpiBZ36B7rox2lmYIYgg5T8qt7tOxo9doAxk=\n"
	const cliPK = "untrusted comment: minisign public key 9149E58DCF22FFC1\nRWTB/yLPjeVJkXKtzk1nZI0TU+fZPqEaIzg1ABHwfnI8pZNWtifIpWBq\n"

	dir := t.TempDir()
	skFile := writeFile(t, dir, "cli.key", cliSK)
	pkFile := writeFile(t, dir, "cli.pub", cliPK)
	f := writeFile(t, dir, "file.txt", "signed by the real CLI key\n")

	if err := signOne(skFile, "testpass", f, ""); err != nil {
		t.Fatalf("sign with real-CLI key: %v", err)
	}
	if _, err := verifyOne(pkFile, f); err != nil {
		t.Fatalf("verify: %v", err)
	}

	// And a key WE generate must be decryptable + verifiable through the
	// library alone (the reverse direction).
	seckey, pubkey, err := generateKeyPair(testPass)
	if err != nil {
		t.Fatal(err)
	}
	oursSK := writeFile(t, dir, "ours.key", string(seckey))
	oursPK := writeFile(t, dir, "ours.pub", string(pubkey))
	f2 := writeFile(t, dir, "file2.txt", "signed by our key\n")
	if err := signOne(oursSK, testPass, f2, ""); err != nil {
		t.Fatal(err)
	}
	if _, err := verifyOne(oursPK, f2); err != nil {
		t.Fatal(err)
	}
}

func TestScryptParams(t *testing.T) {
	// Mirrors libsodium pickparams for the limits we store in keygen.
	N, r, p, err := scryptParamsFromLimits(kdfOpsLimit, kdfMemLimit)
	if err != nil {
		t.Fatal(err)
	}
	if N != 1<<20 || r != 8 || p != 1 {
		t.Fatalf("unexpected scrypt params: N=%d r=%d p=%d", N, r, p)
	}
	// And the interactive limits the older CLI fixtures used.
	if N, r, p, _ := scryptParamsFromLimits(16384, 65536); N != 1<<6 || r != 8 || p != 16 {
		t.Fatalf("unexpected scrypt params (16384/65536): N=%d r=%d p=%d", N, r, p)
	}
}
